In [26]:
import pandas as pd
import pyarrow.dataset as ds



bls = pd.read_excel("data/BLS_4_0_2025_DE/BLS_4_0_Daten_2025_DE.xlsx", nrows=100)
bls = bls.loc[:, ~bls.columns.str.contains("Datenherkunft")]

dataset = ds.dataset("data/food.parquet", format="parquet")

scanner = dataset.scanner(batch_size=100)

batch = next(scanner.to_batches())

off = batch.to_pandas()[["code", "product_name", "nutriments", "ingredients", "categories_tags", "origins"]]

In [19]:
bls

,BLS Code,Lebensmittelbezeichnung,Food name,ENERCJ Energie (Kilojoule) [kJ/100g],ENERCJ Referenz,ENERCC Energie (Kilokalorien) [kcal/100g],ENERCC Referenz,WATER Wasser [g/100g],WATER Referenz,"PROT625 Protein (Nx6,25) [g/100g]",...,THR Referenz,TRP Tryptophan [g/100g],TRP Referenz,TYR Tyrosin [g/100g],TYR Referenz,VAL Valin [g/100g],VAL Referenz,"NT Stickstoff, gesamt [g/100g]",NT Referenz,Hinweis
0,C131000,"Hafer ganzes Korn, roh","Oat whole grain, raw",1443,-,343,-,11.450,"Biel, W., et al.; Chemical composition and nut...",11.375,...,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",0.19,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",0.424,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",0.6425,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",1.724,"Converted value from: Biel, W., et al.; Chemic...",NaN
1,C133000,Hafer Flocken,Oat flakes,1465,-,348,-,10.070,-,13.220,...,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",0.19,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",0.57,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",0.81,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",2.115,-,NaN
2,C141000,"Gerste ganzes Korn, roh","Barley whole grain, raw",1403,-,332,-,12.700,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",11.244,...,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",0.15,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",0.341,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",0.5965,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",1.720,Converted value from: Koivistoinen P; Mineral ...,NaN
3,C243000,Gerste Mehl,Barley flour,1434,-,340,-,6.060,"US Department of Agriculture, Agricultural Res...",11.300,...,"US Department of Agriculture, Agricultural Res...",0.175,"US Department of Agriculture, Agricultural Res...",0.301,"US Department of Agriculture, Agricultural Res...",0.515,"US Department of Agriculture, Agricultural Res...",1.600,"U.S. Department of Agriculture (USDA), Agricul...",NaN
4,C341000,Mais roh,Maize raw,1418,-,336,-,11.192,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",8.656,...,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",0.07725,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",0.3935,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",0.4535,"Kirchhoff, E; Souci - Fachmann - Kraut - Die Z...",1.385,"Converted value from: Kirchhoff, E; Souci - Fa...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,P355000,Most,Apple must,156,-,37,-,91.400,-,0.000,...,-,0,-,0,-,0,-,0.000,-,NaN
96,P733000,Whisky/Whiskey,Whisky/whiskey,957,-,231,-,64.300,"US Department of Agriculture, Agricultural Res...",0.000,...,-,0,-,0,-,0,-,0.000,-,NaN
97,P742000,Arrak,Arrack,887,-,214,-,66.600,-,0.000,...,-,0,-,0,-,0,-,0.000,-,NaN
98,P743000,Rum 80 % vol,Rum 80 % vol,1885,-,455,-,35.000,-,0.000,...,-,0,-,0,-,0,-,0.000,-,NaN
99,P7A4000,Agavenbrand (Mezcal/Tequila),Agave spirit (Mezcal/Tequila),968,-,234,-,66.600,-,0.000,...,-,0,-,0,-,0,-,0.000,-,NaN

In [27]:
off

,code,product_name,nutriments,ingredients,categories_tags,origins
0,0000101209159,"[{'lang': 'main', 'text': 'Véritable pâte à ta...","[{'name': 'energy-kcal', 'value': None, '100g'...",NaN,"[en:breakfasts, en:spreads, en:sweet-spreads, ...",
1,0000105000011,"[{'lang': 'main', 'text': 'Chamomile Herbal Te...",[{'name': 'fruits-vegetables-legumes-estimate-...,"[{""percent_max"":100.0,""percent_min"":100.0,""is_...",[en:null],NaN
2,0000105000042,"[{'lang': 'main', 'text': 'Lagg's, herbal tea,...","[{'name': 'sodium', 'value': 4.0, '100g': 0.00...","[{""percent_max"":100.0,""percent_min"":100.0,""is_...","[en:plant-based-foods-and-beverages, en:bevera...",NaN
3,0000105000059,"[{'lang': 'main', 'text': 'Linden Flowers Tea'...","[{'name': 'energy-kcal', 'value': 213.32000732...","[{""percent_max"":100.0,""percent_min"":100.0,""is_...","[en:beverages-and-beverages-preparations, en:p...",NaN
4,0000105000073,"[{'lang': 'main', 'text': 'Herbal Tea, Hibiscu...","[{'name': 'energy', 'value': 267.0, '100g': 11...","[{""percent_max"":100.0,""percent_min"":100.0,""is_...",None,NaN
...,...,...,...,...,...,...
95,0000651813103,"[{'lang': 'main', 'text': 'Season & Steam Kale...","[{'name': 'fiber', 'value': 2.4000000953674316...","[{""percent_max"":100.0,""percent_min"":100.0,""is_...",None,NaN
96,0000653007548,"[{'lang': 'main', 'text': 'Baguettine aux oliv...","[{'name': 'proteins', 'value': None, '100g': 8...",NaN,None,NaN
97,0000672016408,"[{'lang': 'main', 'text': 'Muffin double choco...","[{'name': 'sugars', 'value': None, '100g': 26....",NaN,"[en:snacks, en:sweet-snacks, en:biscuits-and-c...",NaN
98,0000682009841,"[{'lang': 'main', 'text': 'Pain de campagne bi...","[{'name': 'energy-kj', 'value': None, '100g': ...",NaN,"[en:plant-based-foods-and-beverages, en:plant-...",
99,0000698309041,"[{'lang': 'main', 'text': 'Feletti, Pralines C...","[{'name': 'proteins', 'value': 5.5599999427795...","[{""percent_max"":100.0,""percent_min"":8.33333333...","[en:snacks, en:sweet-snacks, en:cocoa-and-its-...",NaN